networks:
    kzen-backend-network:
        external: true
services:
    service-nodeserverprod:
        container_name: container-nodeserverprod
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8008:8008'
        restart: unless-stopped
        networks:
            - kzen-backend-network
        env_file:
            - .env
