FROM node:alpine

WORKDIR /app

# Copy package files
COPY yarn.lock package.json ./

# Install dependencies
RUN apk --no-cache add bash \
    && npm install -g yarn@1.22.22 --force \
    && yarn install

COPY . ./

RUN yarn build

EXPOSE 8008
EXPOSE 444


# Run your application
CMD ["node", "build/index.mjs"]
