export enum KZEN_ROUTE_ENUM {
    IMAGE_DELETE = '/kzen/image-delete',
    STORY_IMAGE_UPLOAD = '/kzen/story-image-upload',
    STORY_IMAGE_DELETE = '/kzen/story-image-delete',
    ACH_IMAGE_UPLOAD = '/kzen/ach-image-upload',
    ACH_IMAGE_DELETE = '/kzen/ach-image-delete',
    GOAL_SLIDE_IMAGE_UPLOAD = '/kzen/goal-slide-image-upload',
    GOAL_SLIDE_IMAGE_DELETE = '/kzen/goal-slide-image-delete',
    PROFILE_IMAGE_UPLOAD = '/kzen/profile-image-upload',
    PROFILE_IMAGE_DELETE = '/kzen/profile-image-delete',
    SPRINT_IMAGE_UPLOAD = '/kzen/sprint-image-upload',
    SPRINT_IMAGE_DELETE = '/kzen/sprint-image-delete',
    AUTO_RITUALIZE_GOALS = '/kzen/auto-ritualize-goals',
    DESTROY_DATA_URL = '/kzen/destroy-data',
    LOGOUT = '/kzen/logout',
    LOGIN = '/kzen/login',
    LOGIN_REFRESH = '/kzen/login/refresh',
    LOGIN_GOOGLE = '/kzen/google-login',
    REGISTER = '/kzen/register',
    REGISTER_RESEND_ACTIVATION_LINK = '/kzen/register/resend-activation-link',
    REGISTER_VALIDATE_ACTIVATION_CODE = '/kzen/register/validate-activation-code',
    RESTORE = '/kzen/restore',
    NEW_PASSWORD = '/kzen/new-password',
    PROFILE_UPDATE_PASSWORD = '/kzen/update-password',
}
